### ISSUE TITLE
Only works on localhost

### ISSUE THREAD

**Issue by splez** [Spirit55555/PHP-Minecraft#16]
I can't find anyway to run this package on cPanel, it only works on localhost, I try similar packages with the same problem, do I have to something with ports(like firewall or something like that), thanks for any help :)

**Comment by Spirit55555** [comment]
What part of the package does not work? What kind of error do you get?

**Comment by splez** [comment]
it doesn't say, how would one debug this for errors?

**Comment by Spirit55555** [comment]
I can not help you when you do not tell me which part of the package you are using...

I use both on a cPanel server, no problems.

You need access to fsockopen() if you want to use MinecraftVotifier.

This is not an issue with the code, so I'm closing it.

**Comment by splez** [comment]
Thanks, it wasn't anything to do with code, it was because server provider blocked ports for security reasons and I would get ERROR: 111 - Connection refused, the solution is to use VPS or Dedicated server, thanks for the help.
