### ISSUE TITLE
Class 'MinecraftColors' not found

### ISSUE THREAD

**Issue by thebigsmileXD** [Spirit55555/PHP-Minecraft#9]
Class 'MinecraftColors' not found, since the latest PR. I use it on Windows. I still do "include 'MinecraftColors.php';"

**Comment by games647** [comment]
Do you use the "use" statement?

**Comment by thebigsmileXD** [comment]
Actually no, tried it, then it tells me this:
The use statement with non-compound name 'MinecraftColors' has no effect 

```use MinecraftColors;```

**Comment by thebigsmileXD** [comment]
Fail lol.
Thanks for the fast reply.

**Comment by thebigsmileXD** [comment]
use Spirit55555\Minecraft\MinecraftColors;

**Comment by games647** [comment]
Does work it now for you?

**Comment by thebigsmileXD** [comment]
Yes.
